apiVersion: v1
kind: Service
metadata:
  name: {{ include "dar-act-cache.fullname" . }}
  labels:
    {{- include "dar-act-cache.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: cache
      protocol: TCP
      name: cache
  selector:
    {{- include "dar-act-cache.selectorLabels" . | nindent 4 }}

